"""Build notebooks/colab_train_box.ipynb. Run once; the resulting notebook
is committed."""

import json


def md(lines):
    return {"cell_type": "markdown", "metadata": {}, "source": lines}


def code(src):
    return {"cell_type": "code", "metadata": {}, "source": src,
            "outputs": [], "execution_count": None}


cells = []

cells.append(md([
    "# Train the autoregressive model on Colab (boxes or cylinders)\n",
    "\n",
    "One-click GPU run for the **A3 / Stage 2** autoregressive CAD-as-language model.\n",
    "Same recipe (d=256, 5 layers, 100 epochs, ~10k samples) works for either\n",
    "content type; switch via `DATA_KIND` in cell 3.\n",
    "\n",
    "**Setup:** *Runtime → Change runtime type → T4 GPU*, then *Runtime → Run all*.\n",
    "\n",
    "What this does (~15–25 min on a T4):\n",
    "1. Clone the repo, install deps, verify GPU.\n",
    "2. Generate 10k training + 400 held-out scenes for the chosen content (~4 min).\n",
    "3. Train for 100 epochs with d_model=256, 5 decoder layers (~10–18 min on T4).\n",
    "4. Score under F1 + exact-match; compare against the corresponding reference.\n",
    "5. Beam-3 ablation on the same checkpoint.\n",
    "6. Render before/after wireframes.\n",
    "7. (Optional) Save the checkpoint to Google Drive.\n",
    "\n",
    "**Reference points** (boxes is the Stage 1 ship config; cylinders is Unit E6):\n",
    "\n",
    "| Held-out content | F1 | Exact-match |\n",
    "|-----|-----|-----|\n",
    "| classical baseline (boxes) | 0.000 | 0.000 |\n",
    "| AR big preset on **boxes** (Stage 1 ship) | **0.980** | **0.932** |\n",
    "| AR big preset on **cylinders** (this run target) | — | **>= 0.80** |\n",
]))

cells.append(md([
    "## 1. Clone the repo\n",
    "\n",
    "Edit `REPO_URL` below to point at your fork/push of the project.\n",
]))

cells.append(code([
    "REPO_URL = 'https://github.com/Nollis/lines.git'\n",
    "BRANCH = 'main'\n",
    "REPO_DIR = '/content/lines'\n",
    "\n",
    "import os, subprocess\n",
    "if not os.path.isdir(REPO_DIR):\n",
    "    subprocess.check_call(['git', 'clone', '--branch', BRANCH, REPO_URL, REPO_DIR])\n",
    "else:\n",
    "    subprocess.check_call(['git', '-C', REPO_DIR, 'pull', '--ff-only'])\n",
    "os.chdir(REPO_DIR)\n",
    "print('repo at', os.getcwd())\n",
    "print(subprocess.check_output(['git', '-C', REPO_DIR, 'log', '-1', '--oneline']).decode().strip())\n",
]))

cells.append(md(["## 2. Install deps + verify GPU\n"]))

cells.append(code([
    "!pip install -q -e . matplotlib\n",
    "import torch\n",
    "print('torch', torch.__version__, '|  CUDA available:', torch.cuda.is_available())\n",
    "if torch.cuda.is_available():\n",
    "    print('device:', torch.cuda.get_device_name(0))\n",
    "else:\n",
    "    print('NOTE: no GPU. Runtime > Change runtime type > T4 GPU, then Run all again.')\n",
]))

cells.append(md([
    "## 3. Pick the content type\n",
    "\n",
    "Switch this once at the top of the notebook; data dirs, training output dir,\n",
    "and eval references all derive from it. The same recipe ships either kind.\n",
]))

cells.append(code([
    "DATA_KIND = 'mixed'   # 'boxes' | 'cylinders' | 'mixed' (the E7 Stage-2 ship test)\n",
    "\n",
    "# Optional: skip training entirely and load a previously-trained checkpoint\n",
    "# from Google Drive. Set DATA_KIND to match the checkpoint's content type, then\n",
    "# point this at the file on Drive. Leave as None to train fresh.\n",
    "#\n",
    "# Known checkpoints (Drive paths):\n",
    "#   '/content/drive/MyDrive/lines_checkpoints/ar_mixed_64_new.pt'  # iter 2: jitter + wide strokes (current best)\n",
    "#   '/content/drive/MyDrive/ar_mixed_64.pt'                        # earlier mixed run (no jitter)\n",
    "LOAD_FROM_DRIVE = None\n",
    "\n",
    "# Training dirs use _jitter_wide suffix: previous iteration's _jitter run\n",
    "# fixed spatial axes (off_center +0.84 F1, small_scale +0.80 F1) but exposed\n",
    "# stroke_thicker as the new weak axis (-0.18 F1) AND regressed boxes\n",
    "# in-distribution (exact 0.86 -> 0.65). This rebuild widens the stroke range\n",
    "# in sample_render_params (0.6-5.0 px vs 1.5-3.0) AND doubles the training\n",
    "# set to 20k so boxes have enough signal per epoch. Test dirs stay fixed.\n",
    "TRAIN_N = 20_000\n",
    "DATASETS = {\n",
    "    'boxes': {\n",
    "        'script':       'scripts/build_box_data.py',\n",
    "        'train_dir':    'data/train64_box_jitter_wide',\n",
    "        'test_dir':     'data/test64_box',\n",
    "        'out_dir':      'checkpoints/ar_box64_jitter_wide',\n",
    "        'extra_args':   ['--randomize-framing'],\n",
    "        'reference':    'boxes -- Stage 1 (no-jitter) ship: F1=0.980, exact=0.932',\n",
    "    },\n",
    "    'cylinders': {\n",
    "        'script':       'scripts/build_cylinder_data.py',\n",
    "        'train_dir':    'data/train64_cyl_jitter_wide',\n",
    "        'test_dir':     'data/test64_cyl',\n",
    "        'out_dir':      'checkpoints/ar_cyl64_jitter_wide',\n",
    "        'extra_args':   ['--randomize-framing'],\n",
    "        'reference':    'cylinders -- Stage 2 (no-jitter) ship: F1=0.995, exact=0.988',\n",
    "    },\n",
    "    'mixed': {\n",
    "        'script':       'scripts/build_mixed_3d_data.py',\n",
    "        'train_dir':    'data/train64_mixed_3d_jitter_wide',\n",
    "        # eval uses the PURE held-out splits separately (Gate 4: both have to pass)\n",
    "        'test_dir':     'data/test64_box',\n",
    "        'out_dir':      'checkpoints/ar_mixed_3d_jitter_wide',\n",
    "        'extra_args':   ['--fraction-cyl', '0.5', '--randomize-framing'],\n",
    "        'reference':    'mixed + spatial jitter + wide strokes + 20k -- reality-fix iter 2',\n",
    "    },\n",
    "}\n",
    "_cfg = DATASETS[DATA_KIND]\n",
    "BUILD_SCRIPT  = _cfg['script']\n",
    "BUILD_EXTRA   = _cfg['extra_args']\n",
    "TRAIN_DIR     = _cfg['train_dir']\n",
    "TEST_DIR      = _cfg['test_dir']\n",
    "OUT_DIR       = _cfg['out_dir']\n",
    "print(f'DATA_KIND = {DATA_KIND!r}')\n",
    "print(f'  train:  {TRAIN_DIR}')\n",
    "print(f'  test:   {TEST_DIR}  (mixed also evaluates on data/test64_cyl)')\n",
    "print(f'  out:    {OUT_DIR}')\n",
    "print(f'  ref:    {_cfg[\"reference\"]}')\n",
]))

cells.append(md([
    "## 4. Generate data (deterministic seeds -> identical content every time)\n",
]))

cells.append(code([
    "# Test splits always; training set ONLY when actually training (skipped when\n",
    "# LOAD_FROM_DRIVE is set -- no point generating 20k samples to throw away).\n",
    "from pathlib import Path\n",
    "import subprocess\n",
    "\n",
    "tasks = []\n",
    "if LOAD_FROM_DRIVE is None:\n",
    "    tasks.append((TRAIN_DIR, TRAIN_N, 0, BUILD_SCRIPT, BUILD_EXTRA))\n",
    "# always build both pure test splits when DATA_KIND='mixed' so Gate 4 can\n",
    "# measure each content type separately. For 'boxes'/'cylinders' it's a\n",
    "# no-op for the other split (skipped if present, generated otherwise).\n",
    "tasks.append(('data/test64_box', 400, 900_000, 'scripts/build_box_data.py', ['--no-randomize']))\n",
    "if DATA_KIND in ('cylinders', 'mixed'):\n",
    "    tasks.append(('data/test64_cyl', 400, 900_000, 'scripts/build_cylinder_data.py', ['--no-randomize']))\n",
    "\n",
    "for split, n, seed, script, extra in tasks:\n",
    "    if (Path(split) / 'manifest.json').exists():\n",
    "        print(f'{split}: already on disk, skipping')\n",
    "        continue\n",
    "    print(f'generating {split} ({n} samples) via {script}...')\n",
    "    subprocess.check_call(['python', script, '--out', split, '--n', str(n),\n",
    "                            '--seed0', str(seed), '--canvas-side', '64'] + extra)\n",
]))

cells.append(md([
    "## 5. Train (BIG preset: 100 epochs, ~10–18 min on T4)\n",
    "\n",
    "Calls the training function directly so the loss log streams into this cell.\n",
    "Periodic checkpointing every 5 epochs (`OUT_DIR/model.pt`) makes a disconnect\n",
    "safe to resume with `--init-from`.\n",
    "\n",
    "**Skip-training shortcut:** if `LOAD_FROM_DRIVE` is set in cell 3, this cell\n",
    "mounts Drive, copies that file into `OUT_DIR/model.pt`, and skips training so\n",
    "everything downstream (eval, reality probe) runs against the loaded checkpoint.\n",
]))

cells.append(code([
    "from pathlib import Path\n",
    "import shutil\n",
    "from lines.train.train_autoregressive import ARTrainConfig, train_autoregressive\n",
    "\n",
    "if LOAD_FROM_DRIVE is not None:\n",
    "    # eval-only path: mount Drive (no-op if already mounted) and copy the\n",
    "    # checkpoint into the same OUT_DIR that fresh training would have written.\n",
    "    from google.colab import drive\n",
    "    drive.mount('/content/drive', force_remount=False)\n",
    "    src = Path(LOAD_FROM_DRIVE)\n",
    "    if not src.exists():\n",
    "        raise FileNotFoundError(f'LOAD_FROM_DRIVE points at a missing file: {src}')\n",
    "    Path(OUT_DIR).mkdir(parents=True, exist_ok=True)\n",
    "    shutil.copy(src, Path(OUT_DIR) / 'model.pt')\n",
    "    print(f'loaded {src} -> {OUT_DIR}/model.pt (training skipped)')\n",
    "    result = None\n",
    "else:\n",
    "    cfg = ARTrainConfig(\n",
    "        canvas_side=64,\n",
    "        epochs=100,\n",
    "        batch_size=64,\n",
    "        d_model=256,\n",
    "        n_decoder_layers=5,\n",
    "        lr=3e-4,\n",
    "        device='cuda',\n",
    "        checkpoint_every=5,\n",
    "    )\n",
    "    result = train_autoregressive(\n",
    "        cfg,\n",
    "        train_dir=Path(TRAIN_DIR),\n",
    "        test_dir=Path(TEST_DIR),\n",
    "        out_dir=Path(OUT_DIR),\n",
    "    )\n",
]))

cells.append(md([
    "## 6. Score under the honest F1 metric + per-image distribution\n",
    "\n",
    "Mean F1 averages over edges and hides the **distribution** of per-image quality.\n",
    "A 60% perfect / 40% catastrophic mix can still average F1=0.9, but only ~60% of\n",
    "drawings would be *usable*. So we report two extras:\n",
    "\n",
    "* `exact_match_rate` = fraction of held-out drawings reconstructed completely (F1 >= 0.99)\n",
    "* `near_match_rate`  = fraction with at most ~1 wrong edge per 10 (F1 >= 0.9)\n",
]))

cells.append(code([
    "import torch\n",
    "from lines.datagen.dataset import Dataset\n",
    "from lines.datagen.sampler2d import Canvas\n",
    "from lines.eval.harness import run_predictor\n",
    "from lines.models.autoregressive import AutoregressiveModel\n",
    "from lines.train.predictor_ar import AutoregressivePredictor\n",
    "from lines.baselines.classical import ClassicalBaseline\n",
    "\n",
    "from pathlib import Path\n",
    "ck = torch.load(Path(OUT_DIR) / 'model.pt', map_location='cuda', weights_only=False)\n",
    "cfg = ck['cfg']\n",
    "model = AutoregressiveModel(canvas_side=cfg['canvas_side'], d_model=cfg['d_model'],\n",
    "                            n_heads=cfg['n_heads'], n_decoder_layers=cfg['n_decoder_layers'],\n",
    "                            max_seq_len=cfg['max_seq_len']).cuda()\n",
    "model.load_state_dict(ck['model'])\n",
    "\n",
    "C = Canvas(cfg['canvas_side'], cfg['canvas_side'])\n",
    "ar_greedy = AutoregressivePredictor(model, C, max_tokens=cfg['max_seq_len'],\n",
    "                                     device='cuda', beam_size=1)\n",
    "\n",
    "def _score(test_dir):\n",
    "    ds = Dataset(test_dir)\n",
    "    return ds, run_predictor(ar_greedy, ds, C)\n",
    "\n",
    "if DATA_KIND == 'mixed':\n",
    "    # Gate 4: EVAL ON BOTH PURE SPLITS SEPARATELY. averaging would hide a per-\n",
    "    # content regression. boxes must hold >= 0.88, cylinders must hold >= 0.80.\n",
    "    ds_box, r_box = _score('data/test64_box')\n",
    "    ds_cyl, r_cyl = _score('data/test64_cyl')\n",
    "    print('held-out content       F1       Exact   Near')\n",
    "    print(f'boxes      (recorded)  0.980    0.932   0.932')\n",
    "    print(f'cylinders  (recorded)  0.995    0.988   0.988')\n",
    "    print(f'boxes      (this run)  {r_box[\"mean_f1\"]:.3f}    {r_box[\"exact_match_rate\"]:.3f}   {r_box[\"near_match_rate\"]:.3f}')\n",
    "    print(f'cylinders  (this run)  {r_cyl[\"mean_f1\"]:.3f}    {r_cyl[\"exact_match_rate\"]:.3f}   {r_cyl[\"near_match_rate\"]:.3f}')\n",
    "    print()\n",
    "    box_ok = r_box['exact_match_rate'] >= 0.88\n",
    "    cyl_ok = r_cyl['exact_match_rate'] >= 0.80\n",
    "    if box_ok and cyl_ok:\n",
    "        print(f'WIN  GATE 4 passed: boxes {r_box[\"exact_match_rate\"]:.3f} >= 0.88 AND cylinders {r_cyl[\"exact_match_rate\"]:.3f} >= 0.80. One model, both content types. Stage 2 SHIPS.')\n",
    "    elif box_ok and not cyl_ok:\n",
    "        print(f'CYL REGRESSED  cyl {r_cyl[\"exact_match_rate\"]:.3f} < 0.80; cylinders did not survive mixing. Larger model or weighted sampling.')\n",
    "    elif cyl_ok and not box_ok:\n",
    "        print(f'BOX REGRESSED  box {r_box[\"exact_match_rate\"]:.3f} < 0.88 (vs 0.932 pure). Catastrophic interference.')\n",
    "    else:\n",
    "        print(f'BOTH REGRESSED  box {r_box[\"exact_match_rate\"]:.3f}, cyl {r_cyl[\"exact_match_rate\"]:.3f}. Likely undertrained at this mix.')\n",
    "    # use cylinder split for visualization (more interesting content)\n",
    "    ar = ar_greedy; ds = ds_cyl; r_ar = r_cyl\n",
    "else:\n",
    "    ds, r_greedy = _score(TEST_DIR)\n",
    "    r_base = run_predictor(ClassicalBaseline(), ds, C)\n",
    "    print('Predictor                       F1       Exact   Near')\n",
    "    print(f'classical baseline              {r_base[\"mean_f1\"]:.3f}    {r_base[\"exact_match_rate\"]:.3f}   {r_base[\"near_match_rate\"]:.3f}')\n",
    "    if DATA_KIND == 'boxes':\n",
    "        print(f'set predictor + post-process    0.282    (recorded)')\n",
    "        print(f'AR small preset (recorded)      0.899    0.642   0.650')\n",
    "        print(f'AR BIG ({DATA_KIND}, this run)        {r_greedy[\"mean_f1\"]:.3f}    {r_greedy[\"exact_match_rate\"]:.3f}   {r_greedy[\"near_match_rate\"]:.3f}')\n",
    "    else:\n",
    "        print(f'AR boxes (recorded ship)        0.980    0.932   0.932')\n",
    "        print(f'AR BIG ({DATA_KIND}, this run)    {r_greedy[\"mean_f1\"]:.3f}    {r_greedy[\"exact_match_rate\"]:.3f}   {r_greedy[\"near_match_rate\"]:.3f}')\n",
    "    print()\n",
    "    print(f'  perfect drawings: {r_greedy[\"n_perfect\"]}/{r_greedy[\"n\"]}'\n",
    "          f'  ({r_greedy[\"exact_match_rate\"]*100:.1f}%)')\n",
    "    print(f'  near-perfect:     {r_greedy[\"n_near\"]}/{r_greedy[\"n\"]}'\n",
    "          f'  ({r_greedy[\"near_match_rate\"]*100:.1f}%)')\n",
    "    ar = ar_greedy; r_ar = r_greedy\n",
    "    exact_target = 0.85 if DATA_KIND == 'boxes' else 0.80\n",
    "    if r_greedy['exact_match_rate'] >= exact_target:\n",
    "        print(f'WIN  Exact {r_greedy[\"exact_match_rate\"]:.3f} >= {exact_target}: {DATA_KIND} reconstruction ships.')\n",
    "    elif r_greedy['exact_match_rate'] >= 0.60:\n",
    "        print(f'PARTIAL  Exact {r_greedy[\"exact_match_rate\"]:.3f}: still improving. Try +50 epochs (warm-start) or larger model.')\n",
    "    else:\n",
    "        print(f'PLATEAU  Exact {r_greedy[\"exact_match_rate\"]:.3f}: capacity may not be the bottleneck. Inspect which views fail.')\n",
]))

cells.append(md([
    "## 6b. Beam search vs greedy on the *same* trained model\n",
    "\n",
    "Greedy is myopic -- once it picks a bad token, the rest cascades (the row-3\n",
    "catastrophe in the panel below). Beam-3 explores 3 paths and reduces that\n",
    "rate. No retraining; just a different decoder. Slower than greedy on CPU but\n",
    "comparable on GPU; expect ~+0.02 to ~+0.05 F1 and a bigger jump on\n",
    "`exact_match_rate`.\n",
]))

cells.append(code([
    "# Use r_ar (set by the previous cell) as the greedy reference. For mixed mode\n",
    "# r_ar is the cylinder-split score; for pure modes it's the single test score.\n",
    "ar_beam = AutoregressivePredictor(model, C, max_tokens=cfg['max_seq_len'],\n",
    "                                   device='cuda', beam_size=3)\n",
    "r_beam = run_predictor(ar_beam, ds, C)\n",
    "print('Predictor                       F1       Exact   Near')\n",
    "print(f'AR greedy (this run)            {r_ar[\"mean_f1\"]:.3f}    {r_ar[\"exact_match_rate\"]:.3f}   {r_ar[\"near_match_rate\"]:.3f}')\n",
    "print(f'AR beam-3 (this run)            {r_beam[\"mean_f1\"]:.3f}    {r_beam[\"exact_match_rate\"]:.3f}   {r_beam[\"near_match_rate\"]:.3f}')\n",
    "print()\n",
    "delta_f1 = r_beam['mean_f1'] - r_ar['mean_f1']\n",
    "delta_exact = r_beam['exact_match_rate'] - r_ar['exact_match_rate']\n",
    "print(f'beam vs greedy: dF1 = {delta_f1:+.3f}  dExact = {delta_exact:+.3f}')\n",
    "# use the better predictor for the visualization cell\n",
    "if r_beam['mean_f1'] > r_ar['mean_f1']:\n",
    "    ar = ar_beam\n",
    "    print('-> using beam-3 for the visualization below')\n",
]))

cells.append(md([
    "## 7. Eyeball the wireframes\n",
    "\n",
    "Six held-out boxes: input | model prediction | ground truth.\n",
]))

cells.append(code([
    "import matplotlib.pyplot as plt\n",
    "from lines.datagen.render import render_primitives\n",
    "\n",
    "N = 6\n",
    "fig, axes = plt.subplots(N, 3, figsize=(7, 2.2 * N))\n",
    "for k in range(N):\n",
    "    img, gt = ds[k]\n",
    "    pred = ar(img)\n",
    "    pred_img = render_primitives(pred, C.width, C.height)\n",
    "    gt_img = render_primitives(gt, C.width, C.height)\n",
    "    for ax, im, title in zip(axes[k], [img, pred_img, gt_img],\n",
    "                              ['input', 'prediction', 'ground truth']):\n",
    "        ax.imshow(im, cmap='gray', vmin=0, vmax=255)\n",
    "        ax.set_title(title if k == 0 else ''); ax.axis('off')\n",
    "plt.tight_layout(); plt.show()\n",
]))

cells.append(md([
    "## 7b. Reality check: perturbation probes\n",
    "\n",
    "We've trained on a very specific distribution: orthographic, fixed view-jitter,\n",
    "Pillow + supersampling at 1.5-3 px strokes, auto-fit to canvas. Any real input\n",
    "differs along multiple axes. Each probe perturbs the held-out test data along\n",
    "**one axis at a time** so we can see which shifts the model survives and which\n",
    "break it.\n",
    "\n",
    "* `baseline`       -- control (no perturbation)\n",
    "* `cv2`            -- different rasterizer (OpenCV; different AA + endpoints)\n",
    "* `jpeg`           -- JPEG roundtrip at q=60 (the project's inputs are .jpg)\n",
    "* `stroke_thicker` -- 4.5 px (outside training 1.5-3 range)\n",
    "* `stroke_thinner` -- 0.8 px (outside training)\n",
    "* `off_center`     -- random translation (our generator always centers)\n",
    "* `small_scale`    -- object only fills ~40% of canvas\n",
    "\n",
    "Each probe runs ~200 samples through the trained model and reports F1 +\n",
    "exact-match. The drop from `baseline` is the sim-to-real cost for that axis.\n",
]))

cells.append(code([
    "import numpy as np\n",
    "from lines.datagen.realityprobe import PERTURBATIONS, make_probe_sample\n",
    "from lines.eval.metrics import evaluate\n",
    "\n",
    "PROBE_N = 200\n",
    "# probe the cylinder split if available (more interesting content); fall back to box\n",
    "probe_test_dir = 'data/test64_cyl' if Path('data/test64_cyl/manifest.json').exists() else 'data/test64_box'\n",
    "probe_ds = Dataset(probe_test_dir)\n",
    "n_probe = min(PROBE_N, len(probe_ds))\n",
    "print(f'probing against {probe_test_dir} (first {n_probe} samples)')\n",
    "print()\n",
    "\n",
    "rows = []\n",
    "for name in ['baseline', 'cv2', 'jpeg', 'stroke_thicker', 'stroke_thinner',\n",
    "             'off_center', 'small_scale']:\n",
    "    f1s, exact = [], 0\n",
    "    for i in range(n_probe):\n",
    "        _, gt_base = probe_ds[i]\n",
    "        img, gt = make_probe_sample(gt_base, C, name, seed=i * 31 + 1)\n",
    "        pred = ar(img)\n",
    "        m = evaluate(pred, gt, C)\n",
    "        f1s.append(m['f1'])\n",
    "        if m['f1'] >= 0.99:\n",
    "            exact += 1\n",
    "    mean_f1 = float(np.mean(f1s))\n",
    "    exact_rate = exact / n_probe\n",
    "    rows.append((name, mean_f1, exact_rate))\n",
    "\n",
    "baseline_f1, baseline_exact = rows[0][1], rows[0][2]\n",
    "print('perturbation         F1     Exact     dF1       dExact')\n",
    "print('-' * 60)\n",
    "for name, f1, ex in rows:\n",
    "    df = f1 - baseline_f1\n",
    "    de = ex - baseline_exact\n",
    "    marker = '  <-- baseline' if name == 'baseline' else ''\n",
    "    print(f'  {name:18s} {f1:.3f}  {ex:.3f}    {df:+.3f}    {de:+.3f}{marker}')\n",
    "print()\n",
    "worst_name = min(rows[1:], key=lambda r: r[1])[0]\n",
    "best_name = max(rows[1:], key=lambda r: r[1])[0]\n",
    "print(f'most robust axis:   {best_name}')\n",
    "print(f'most fragile axis:  {worst_name}  <-- this is where to focus domain randomization')\n",
]))

cells.append(md([
    "## 7c. Worst-case visual: 6 samples from the most fragile probe\n",
]))

cells.append(code([
    "import matplotlib.pyplot as plt\n",
    "from lines.datagen.realityprobe import make_probe_sample\n",
    "from lines.datagen.render import render_primitives\n",
    "from lines.eval.metrics import evaluate\n",
    "\n",
    "# pick 6 samples from the most fragile probe, sorted by WORST F1\n",
    "samples = []\n",
    "for i in range(min(60, len(probe_ds))):\n",
    "    _, gt_base = probe_ds[i]\n",
    "    img, gt = make_probe_sample(gt_base, C, worst_name, seed=i * 31 + 1)\n",
    "    pred = ar(img)\n",
    "    f1 = evaluate(pred, gt, C)['f1']\n",
    "    samples.append((f1, img, pred, gt))\n",
    "samples.sort(key=lambda s: s[0])\n",
    "samples = samples[:6]\n",
    "\n",
    "fig, axes = plt.subplots(6, 3, figsize=(7, 2.2 * 6))\n",
    "for k, (f1, img, pred, gt) in enumerate(samples):\n",
    "    pred_img = render_primitives(pred, C.width, C.height)\n",
    "    gt_img = render_primitives(gt, C.width, C.height)\n",
    "    for ax, im, title in zip(axes[k], [img, pred_img, gt_img],\n",
    "                              [f'{worst_name} input  (F1={f1:.2f})', 'prediction', 'ground truth']):\n",
    "        ax.imshow(im, cmap='gray', vmin=0, vmax=255)\n",
    "        ax.set_title(title if k == 0 else (f'F1={f1:.2f}' if title.startswith(worst_name) else '')); ax.axis('off')\n",
    "plt.tight_layout(); plt.show()\n",
]))

cells.append(md([
    "## 7d. Real-image probe: actual CAD / SketchUp / OnShape exports\n",
    "\n",
    "Every probe up to this point perturbed *our own* generator's output.\n",
    "This section runs the model on images the generator never touched -- the\n",
    "final reality check the project was built to answer.\n",
    "\n",
    "**Setup (once):** put a handful of real CAD/SketchUp/OnShape wireframe\n",
    "exports as PNG/JPG into\n",
    "\n",
    "    /content/drive/MyDrive/lines_real_probe/\n",
    "\n",
    "Anything goes -- mixed sizes, mixed line weights, with or without\n",
    "backgrounds. The cell auto-preprocesses to the model's 64x64 grayscale\n",
    "input (handles white-on-black inputs by inverting polarity) and shows\n",
    "input | preprocessed | prediction for each.\n",
    "\n",
    "**No hand-labeled ground truth required for v1** -- this is qualitative.\n",
    "Look at the prediction column: do the recovered primitives match the\n",
    "intended geometry? That's the answer.\n",
]))

cells.append(code([
    "from pathlib import Path\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "from lines.datagen.render import render_primitives\n",
    "\n",
    "REAL_PROBE_DIR = '/content/drive/MyDrive/lines_real_probe'\n",
    "\n",
    "# mount Drive if we haven't yet (safe no-op if already mounted)\n",
    "try:\n",
    "    from google.colab import drive\n",
    "    drive.mount('/content/drive', force_remount=False)\n",
    "except ImportError:\n",
    "    pass\n",
    "\n",
    "probe_root = Path(REAL_PROBE_DIR)\n",
    "if not probe_root.exists():\n",
    "    print(f'NOTE: {probe_root} does not exist on Drive yet.')\n",
    "    print('Create it and drop some CAD wireframe PNG/JPGs in, then re-run this cell.')\n",
    "else:\n",
    "    files = sorted([p for p in probe_root.iterdir()\n",
    "                    if p.suffix.lower() in {'.png', '.jpg', '.jpeg', '.bmp', '.tif'}])\n",
    "    if not files:\n",
    "        print(f'NOTE: {probe_root} is empty. Drop some images in to probe.')\n",
    "    else:\n",
    "        print(f'found {len(files)} real images')\n",
    "        S = cfg['canvas_side']\n",
    "        rows_real = []\n",
    "        for f in files:\n",
    "            raw = Image.open(f).convert('L')\n",
    "            # auto-polarity: if mean > 128 the input is dark-on-light (good);\n",
    "            # else assume light-on-dark and invert.\n",
    "            arr = np.asarray(raw, dtype=np.uint8)\n",
    "            if arr.mean() < 128:\n",
    "                arr = 255 - arr\n",
    "                raw = Image.fromarray(arr, 'L')\n",
    "            pre = raw.resize((S, S), Image.LANCZOS)\n",
    "            pre_arr = np.asarray(pre, dtype=np.uint8)\n",
    "            pred = ar(pre_arr)\n",
    "            pred_img = render_primitives(pred, S, S) if pred.primitives else np.full((S, S), 255, np.uint8)\n",
    "            rows_real.append((f.name, np.asarray(raw), pre_arr, pred_img, len(pred.primitives)))\n",
    "\n",
    "        N = len(rows_real)\n",
    "        fig, axes = plt.subplots(N, 3, figsize=(9, 3.0 * N))\n",
    "        if N == 1:\n",
    "            axes = axes.reshape(1, 3)\n",
    "        n_nonempty = 0\n",
    "        for k, (name, raw_arr, pre_arr, pred_img, n_prims) in enumerate(rows_real):\n",
    "            n_nonempty += int(n_prims > 0)\n",
    "            titles = [f'{name} ({raw_arr.shape[1]}x{raw_arr.shape[0]})',\n",
    "                      f'preprocessed -> {S}x{S}',\n",
    "                      f'prediction ({n_prims} primitives)']\n",
    "            for ax, im, t in zip(axes[k], [raw_arr, pre_arr, pred_img], titles):\n",
    "                ax.imshow(im, cmap='gray', vmin=0, vmax=255)\n",
    "                ax.set_title(t); ax.axis('off')\n",
    "        plt.tight_layout(); plt.show()\n",
    "        print(f'\\nproduced primitives for {n_nonempty}/{N} images')\n",
    "        print('(qualitative judgement: do the prediction primitives match the input geometry?)')\n",
]))

cells.append(md([
    "## 8. (Optional) Save the trained checkpoint to Google Drive\n",
    "\n",
    "Colab sessions get reaped. Uncomment to persist the checkpoint.\n",
]))

cells.append(code([
    "# from google.colab import drive\n",
    "# drive.mount('/content/drive')\n",
    "# !mkdir -p /content/drive/MyDrive/lines_checkpoints\n",
    "# import shutil\n",
    "# dst = f'/content/drive/MyDrive/lines_checkpoints/ar_{DATA_KIND}_64.pt'\n",
    "# shutil.copy(f'{OUT_DIR}/model.pt', dst)\n",
    "# print(f'saved to Drive: {dst}')\n",
]))

nb = {"cells": cells,
      "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                   "language_info": {"name": "python"},
                   "accelerator": "GPU", "colab": {"provenance": []}},
      "nbformat": 4, "nbformat_minor": 5}

with open("notebooks/colab_train_box.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print(f"wrote notebooks/colab_train_box.ipynb ({len(cells)} cells)")
